# Generated by Django 5.0.4 on 2024-07-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Appecom", "0003_alter_basketproduct_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="basketproduct",
            name="prod_total_price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
