# Generated by Django 5.0.4 on 2024-07-24 15:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Appecom", "0004_basketproduct_prod_total_price"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BasketProduct",
        ),
    ]
