# Generated by Django 5.0.4 on 2024-07-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Appecom", "0006_basketproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basketproduct",
            name="prod_total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
    ]
