# Generated by Django 5.0.4 on 2024-07-29 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Appecom", "0007_alter_basketproduct_prod_total_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.RemoveField(
            model_name="order",
            name="quantity",
        ),
        migrations.AddField(
            model_name="order",
            name="prod_total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField()),
                ("il", models.CharField(max_length=50)),
                ("ilce", models.CharField(max_length=50)),
                ("posta_kodu", models.IntegerField()),
                (
                    "profil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Appecom.profil"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Appecom.address"
            ),
        ),
        migrations.CreateModel(
            name="OrderItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "prod_total_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Appecom.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="order_items",
            field=models.ManyToManyField(to="Appecom.orderitems"),
        ),
    ]
