# Generated by Django 5.0.4 on 2024-07-29 14:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Appecom", "0008_remove_order_product_remove_order_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
    ]
